export const mockJobs = [
  {
    id: "job-001",
    title: "Automation Control Practitioner",
    role: "Automation Control Practitioner",
    company: "Accenture",
    companyName: "Accenture",
    recruiter: "Suman Gupta",
    recruiterName: "Suman Gupta",
    sentAt: "Sent today at 10:30 AM",
    matchReason:
      "Your PLM and Siemens Teamcenter experience matches this opening.",
    recruiterDetails: {
      id: "rec-001",
      name: "Suman Gupta",
      designation: "Senior Technical Recruiter",
      company: "Accenture",
      email: "suman.gupta@accenture.com",
      phone: "+91 98765 43210",
      location: "Pune, India",
      linkedin: "linkedin.com/in/suman-gupta",
      responseTime: "Usually replies within 1 day",
    },
    type: "Full-Time",
    employmentType: "Full-Time",
    location: "Pune",
    city: "Pune",
    experience: "2-5 years",
    salary: "Not Disclosed",
    postedAt: "12 hours ago",
    views: 2,
    applyUrl: "https://www.accenture.com/in-en/careers",
    skills: [
      "Siemens Teamcenter",
      "PLM Development",
      "Solution Design",
      "BMIDE",
      "ITK",
      "RAC Customization",
    ],
    description:
      "Project Role: Automation Control Practitioner\n\nDevelop and implement automation processes for enterprise applications. Work with product owners, engineers, and delivery teams to improve workflow efficiency, support integrations, and maintain scalable automation solutions.\n\nKey Responsibilities:\n- Build and maintain automation workflows.\n- Collaborate with cross-functional teams.\n- Troubleshoot application and integration issues.\n- Document technical designs and implementation notes.",
  },
  {
    id: "job-002",
    title: "Director - Platform Engineering",
    role: "Director - Platform Engineering",
    company: "Mastercard",
    companyName: "Mastercard",
    recruiter: "Rahul Mehta",
    recruiterName: "Rahul Mehta",
    sentAt: "Sent yesterday at 4:15 PM",
    matchReason:
      "Your leadership background and platform engineering skills are a strong fit.",
    recruiterDetails: {
      id: "rec-002",
      name: "Rahul Mehta",
      designation: "Director - Talent Acquisition",
      company: "Mastercard",
      email: "rahul.mehta@mastercard.com",
      phone: "+91 99887 77665",
      location: "Pune, India",
      linkedin: "linkedin.com/in/rahul-mehta",
      responseTime: "Usually replies within 2 days",
    },
    type: "Full-Time",
    employmentType: "Full-Time",
    location: "Pune",
    city: "Pune",
    experience: "10+ years",
    salary: "Not Disclosed",
    postedAt: "12 hours ago",
    views: 0,
    applyUrl: "https://www.mastercard.com/global/en/vision/corp-responsibility/careers.html",
    skills: [
      "Platform Engineering",
      "Big Data",
      "Data Engineering",
      "Java",
      "Python",
      "React",
      "Next.js",
      "SQL",
    ],
    description:
      "Lead platform engineering teams responsible for building reliable, scalable, and secure engineering platforms. Partner with business and technology leaders to define engineering strategy, improve developer experience, and deliver high-impact systems.\n\nKey Responsibilities:\n- Own platform architecture and engineering roadmap.\n- Mentor senior engineers and managers.\n- Improve reliability, observability, and release processes.\n- Drive standards for cloud, data, and application platforms.",
  },
  {
    id: "job-003",
    title: "Sr. Web Developer (Full Stack)",
    role: "Sr. Web Developer (Full Stack)",
    company: "Mastercard",
    companyName: "Mastercard",
    recruiter: "Neha Sharma",
    recruiterName: "Neha Sharma",
    sentAt: "Sent 2 days ago",
    matchReason:
      "Your React, Node.js, and TypeScript profile matched the full-stack role.",
    recruiterDetails: {
      id: "rec-003",
      name: "Neha Sharma",
      designation: "Talent Partner",
      company: "Mastercard",
      email: "neha.sharma@mastercard.com",
      phone: "+91 91234 56780",
      location: "Bengaluru, India",
      linkedin: "linkedin.com/in/neha-sharma",
      responseTime: "Usually replies within 24 hours",
    },
    type: "Full-Time",
    employmentType: "Full-Time",
    location: "Bengaluru",
    city: "Bengaluru",
    experience: "5-8 years",
    salary: "18-28 LPA",
    postedAt: "1 day ago",
    views: 14,
    applyUrl: "https://www.mastercard.com/global/en/vision/corp-responsibility/careers.html",
    skills: [
      "React",
      "Node.js",
      "TypeScript",
      "REST APIs",
      "MongoDB",
      "Tailwind CSS",
    ],
    description:
      "Build and maintain full-stack web applications with a strong focus on performance, clean UI, and reliable backend APIs. You will work closely with product, design, and engineering teams to ship user-facing features.\n\nKey Responsibilities:\n- Develop reusable frontend components.\n- Build secure backend APIs.\n- Optimize application performance.\n- Participate in code reviews and technical planning.",
  },
  {
    id: "job-004",
    title: "Lead - Full Stack Web Applications",
    role: "Lead - Full Stack Web Applications",
    company: "Mastercard",
    companyName: "Mastercard",
    recruiter: "Amit Verma",
    recruiterName: "Amit Verma",
    sentAt: "Sent 3 days ago",
    matchReason:
      "Your full-stack leadership and system design experience match this lead opening.",
    recruiterDetails: {
      id: "rec-004",
      name: "Amit Verma",
      designation: "Lead Recruiter",
      company: "Mastercard",
      email: "amit.verma@mastercard.com",
      phone: "+91 90909 12121",
      location: "Hyderabad, India",
      linkedin: "linkedin.com/in/amit-verma",
      responseTime: "Usually replies within 1-2 days",
    },
    type: "Full-Time",
    employmentType: "Full-Time",
    location: "Hyderabad",
    city: "Hyderabad",
    experience: "8-12 years",
    salary: "Not Disclosed",
    postedAt: "2 days ago",
    views: 9,
    applyUrl: "https://www.mastercard.com/global/en/vision/corp-responsibility/careers.html",
    skills: [
      "React",
      "Java",
      "Spring Boot",
      "Microservices",
      "AWS",
      "System Design",
    ],
    description:
      "Lead delivery of full-stack web applications across frontend and backend systems. Define technical direction, unblock engineering teams, and ensure applications are scalable, maintainable, and production-ready.\n\nKey Responsibilities:\n- Lead application architecture decisions.\n- Review code and mentor developers.\n- Coordinate with stakeholders for delivery planning.\n- Improve engineering quality and release confidence.",
  },
];

export default mockJobs;
